[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
regex = "1.11.1"
strum = "0.26.3"
strum_macros = "0.26.4"
rayon = "1.10.0"
im = { version = "*", features = ["proptest", "serde"] }
chrono = "0.4.39"
